# NB: don't set `language: haskell` here

# The following enables several GHC versions to be tested; often it's enough to
# test only against the last release in a major GHC version. Feel free to omit
# lines listings versions you don't need/want testing for.
env:
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=7.8.4
 - GHCVER=7.10.3
 - GHCVER=8.0.1 TEST_OLDER=NO
 # TODO add PARSEC_BUNDLED=YES when it's so
 # It seems pointless to run head if we're going to ignore the results.
 #- GHCVER=head

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install --force-yes ghc-$GHCVER-prof ghc-$GHCVER-dyn happy
 - if [ "$TEST_OLDER" == "YES" ]; then travis_retry sudo apt-get install --force-yes ghc-7.0.4-prof ghc-7.0.4-dyn ghc-7.2.2-prof ghc-7.2.2-dyn; fi
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/1.24/bin:$PATH
 - git version

 # Set up deployment to the haskell/cabal-website repo.
 - git clone --depth=50 --branch=gh-pages https://github.com/haskell/cabal-website.git ../cabal-website
 - cd ../cabal-website
 - openssl aes-256-cbc -K $encrypted_edaf6551664d_key -iv $encrypted_edaf6551664d_iv -in id_ed25519_cabal_website.aes256.enc -out id_ed25519 -d
 - mv id_ed25519 ~/.ssh/id_ed25519
 - chmod 400 ~/.ssh/id_ed25519
 - cd -

install:
 # We intentionally do not install anything before trying to build Cabal because
 # it should build with each supported GHC version out-of-the-box.

# Here starts the actual work to be performed for the package under test; any
# command which exits with a non-zero exit code causes the build to fail. Using
# ./dist/setup/setup here instead of cabal-install to avoid breakage when the
# build config format changed.
script:
 - ./travis-script.sh -j

# Deploy Haddocks to the haskell/cabal-website repo.
after_success:
 - git config --global user.email "builds@travis-ci.org"
 - git config --global user.name "Travis CI User"
 - mkdir -p ../cabal-website/doc/html
 - mv Cabal/dist/doc/html/Cabal ../cabal-website/doc/html/Cabal
 - cd ../cabal-website
 - git add .
 - git commit --amend -m "Deploy to GitHub ($(date))."
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && git push --force --quiet git@github.com:haskell/haskell-website.git gh-pages

matrix:
  allow_failures:
   - env: GHCVER=head

notifications:
  irc:
    channels:
      - "chat.freenode.net##haskell-cabal"
  slack: haskell-cabal:sCq6GLfy9N8MJrInosg871n4
