resolver: nightly-2017-11-01
packages:
- Cabal/
- cabal-install/
- cabal-testsuite/
nix:
  packages:
  - autoconf
  - automake
  - haskellPackages.happy
  - haskellPackages.alex
  - zlib
  - zlib.out
