resolver: lts-18.28 # ghc-8.10.7

packages:
- Cabal-syntax/
- Cabal/
- Cabal-described
- Cabal-QuickCheck/
- Cabal-tests/
- Cabal-tree-diff/
- cabal-benchmarks/
- cabal-install-solver/
- cabal-install/
- cabal-testsuite/
- solver-benchmarks/

extra-deps:
- rere-0.2@rev:1

allow-newer: true

nix:
  packages:
  - autoconf
  - automake
  - haskellPackages.happy
  - haskellPackages.alex
  - zlib
  - zlib.out
